module.exports = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quickstart',
        'getting-started/account-setup',
        'getting-started/workspace-setup',
        'getting-started/first-whatsapp-number',
        'getting-started/sandbox-mode',
        'getting-started/production-checklist',
      ],
    },
    {
      type: 'category',
      label: 'Fundamentals',
      items: [
        'fundamentals/platform-overview',
        'fundamentals/key-concepts',
        'fundamentals/architecture',
        'fundamentals/messaging-lifecycle',
        'fundamentals/conversation-pricing',
        'fundamentals/template-messaging',
        'fundamentals/session-messaging',
        'fundamentals/data-model',
        'fundamentals/rate-limits',
        'fundamentals/error-model',
      ],
    },
    {
      type: 'category',
      label: 'WhatsApp Cloud API',
      items: [
        'whatsapp-cloud-api/overview',
        'whatsapp-cloud-api/meta-app-setup',
        'whatsapp-cloud-api/system-user-token',
        'whatsapp-cloud-api/phone-number-onboarding',
        'whatsapp-cloud-api/webhook-subscriptions',
        'whatsapp-cloud-api/message-types',
        'whatsapp-cloud-api/interactive-messages',
        'whatsapp-cloud-api/media-messages',
        'whatsapp-cloud-api/template-management',
        'whatsapp-cloud-api/quality-rating',
        'whatsapp-cloud-api/throughput-scaling',
        'whatsapp-cloud-api/migration',
      ],
    },
    {
      type: 'category',
      label: 'Automation',
      items: [
        'automation/automation-overview',
        'automation/workflow-builder',
        'automation/trigger-types',
        'automation/conditions-filters',
        'automation/actions-catalog',
        'automation/fallback-routing',
        'automation/ai-agent-basics',
        'automation/human-handoff',
        'automation/scheduling-retries',
        'automation/testing-automation',
        'automation/workflow-versioning',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        'integrations/crm-salesforce',
        'integrations/crm-hubspot',
        'integrations/zapier',
        'integrations/n8n',
        'integrations/shopify',
        'integrations/woocommerce',
        'integrations/google-sheets',
        'integrations/webhooks-outbound',
        'integrations/rest-api',
        'integrations/events-stream',
      ],
    },
    {
      type: 'category',
      label: 'Analytics',
      items: [
        'analytics/dashboard-overview',
        'analytics/delivery-reports',
        'analytics/funnel-analysis',
        'analytics/agent-performance',
        'analytics/campaign-attribution',
        'analytics/custom-reports',
        'analytics/exporting-data',
        'analytics/alerting-anomalies',
      ],
    },
    {
      type: 'category',
      label: 'Security & Compliance',
      items: [
        'security/security-overview',
        'security/rbac',
        'security/api-keys',
        'security/secrets-management',
        'security/data-retention',
        'security/encryption',
        'security/gdpr',
        'security/dpa-soc2',
        'security/ip-allowlist',
        'security/audit-logs',
      ],
    },
    {
      type: 'category',
      label: 'Developer',
      items: [
        'developer/api-authentication',
        'developer/send-message-endpoint',
        'developer/contacts-endpoint',
        'developer/templates-endpoint',
        'developer/webhooks-reference',
        'developer/error-codes',
        'developer/sdks',
        'developer/postman-collection',
        'developer/testing-sandbox',
        'developer/go-live-checklist',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/sla-slos',
        'operations/incident-response',
        'operations/status-page',
        'operations/backup-recovery',
        'operations/cost-optimization',
        'operations/scaling-playbook',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/lead-qualification-bot',
        'tutorials/order-updates-bot',
        'tutorials/abandoned-cart-recovery',
        'tutorials/appointment-reminders',
        'tutorials/multi-language-bot',
        'tutorials/support-escalation-flow',
        'tutorials/broadcast-campaign-playbook',
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [
        'faq/general-faq',
        'faq/billing-faq',
        'faq/deliverability-faq',
        'faq/troubleshooting-faq',
      ],
    },
  ],
};
